[tool.poetry]
name = "downloads-cleaner"
version = "0.1.0"
description = ""
authors = ["Danylo Zdoryk <danylozdoryk1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
